export const ADD_OPTION = "ADD_OPTION";
export const TOGGLE_COMPLETION = "TOGGLE_COMPLETION";
export const REMOVE_ALL = 'REMOVE_ALL';
export const REMOVE_OPTION = 'REMOVE_OPTION'; 
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const COMPLETE_ALL = 'COMPLETE_ALL';

export const visibilityFilters = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_UNCOMPLETED: 'SHOW_UNCOMPLETED'
}